#!/bin/bash
set -ev

export TRAVIS_DEBUG_MODE="true"

echo Default Environment Variables
echo TRAVIS_BUILD_NUMBER = $TRAVIS_BUILD_NUMBER
echo TRAVIS_ALLOW_FAILURE = $TRAVIS_ALLOW_FAILURE
echo TRAVIS_BRANCH = $TRAVIS_BRANCH
echo TRAVIS_BUILD_DIR = $TRAVIS_BUILD_DIR
echo TRAVIS_BUILD_WEB_URL = $TRAVIS_BUILD_WEB_URL
echo TRAVIS_DEBUG_MODE = $TRAVIS_DEBUG_MODE
echo TRAVIS_DIST = $TRAVIS_DIST
echo TRAVIS_EVENT_TYPE = $TRAVIS_EVENT_TYPE

echo Job
echo TRAVIS_JOB_ID = $TRAVIS_JOB_ID
echo TRAVIS_JOB_NAME = $TRAVIS_JOB_NAME
echo TRAVIS_JOB_NUMBER = $TRAVIS_JOB_NUMBER
echo TRAVIS_JOB_WEB_URL = $TRAVIS_JOB_WEB_URL